### ISSUE TITLE
CSS missing

### ISSUE THREAD

**Issue by netbe** [klaxpont/klaxpont-web#2]
y a plus de css sur http://klaxpont.herokuapp.com

**Comment by farnoux** [comment]
Bon chelou, ca aurait dû ne plus fonctionner depuis l'update à Rails 3.2.2. Je ne comprend pas pourquoi on a eu ca que maintenant, mais en gros un problème avec l'asset pipeline qui ne fonctionnait plus pcq j'avais commenté un truc lors de l'upgrade (`sprockets/railtie`).
C'est bon maintenant !
